[package]
org = "ballerina"
name = "observe"
version = "1.8.0-alpha"
distribution = "2201.13.0"

[[package.modules]]
name = "observe.mockextension"
description = "This module provides mock extension to observe Ballerina applications."
export = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/observe-native-1.8.0-alpha.jar"
groupId = "ballerina"
artifactId = "observe"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-trace"
version = "1.0.0"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-testing"
version = "1.0.0"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-common"
version = "1.0.0"

[[platform.java21.dependency]]
groupId = "io.opentelemetry"
artifactId = "opentelemetry-semconv"
version = "1.0.0-alpha"
